### PR TITLE
Frontend Challenge - Giovana Niehues

### PR DESCRIPTION
**Pull request by ngiovana**
# Sizebay Project - To-do app

This project is a To-Do list application created with [Create Sizebay App](https://github.com/sizebay/create-szb-app).

### Prerequisites

Before running the project, make sure you have Node.js installed in your environment:

### Installation

Follow these steps to install and set up the project locally:

1. Clone the repository to your workspace:

   ```bash
   git clone https://github.com/ngiovana/frontend-challenge.git
   ```

2. Navigate to the project directory:
   ```bash
   cd frontend-challenge
   ```

3. Install dependencies
   ```bash
   npm install
   ```

4. Start the project
   ```bash
   npm run start
   ```

Runs the app in the development mode.
Open [http://localhost:3000](http://localhost:3000) to view it on browser.

### CODE REVIEW

**Comment by vaporwavie** [comment]
Hello @ngiovana, thanks for your submission! @breno5g will take a look and do the Code Review.

Usually, our time frame can be defined as:

- 1st submission
- 2nd submission after CR is made (if necessary)
- Final thoughts and feedback

Thanks!

**Comment by vaporwavie** [comment]
@ngiovana let us know when your part is completed so we can start reviewing it.

**Comment by ngiovana** [comment]
@vaporwavie I made some adjustments but now it's ready for review!

**Comment by ngiovana** [comment]
Hello @breno5g, I made some corrections and the PR is now ready for the 2nd review.

**Review by breno5g — APPROVED** [review]
## Errors
- search input does't work.
- create task button does't work
- text with more than one word breaks the line
- It is still possible to bug the task editing when selecting to edit and use the filters.
## Suggestions for improvements
Automatically focusing on the input when editing a task allows the user to better locate themselves in relation to the action performed.
Creating a context is intended to create global access state and prevent prop drilling. But in the current implementation, we still have a considerable amount of props being passed to the components, which are within the task provider.
## Final considerations
Considering that this is a mid-level position, the initiative to create tests and documentation would be interesting.
But overall, I liked the improvements I saw here and it's good to see that you managed to resolve much of what was highlighted in the previous code review.

Thank you for participating in the technical test and we will get back to you as soon as possible with the next steps.

**Comment by vaporwavie** [comment]
Thank you @ngiovana! We'll contact you soon. Closing this PR and accepting the submission.

**Pull request closed without merging**
