### PR TITLE
[Luciana Cunha] - Frontend Challenge

### PR DESCRIPTION
**Pull request by luc0liv**
# Sizebay - Frontend Challenge

### How to run this project:

Clone the project:
#### `git clone https://github.com/luc0liv/frontend-challenge.git`

Go to the project directory:

#### `cd frontend-challenge` 

In the project directory, you can run:

#### `npm run wrap`

Open [http://localhost:3000](http://localhost:3000) to view it in the browser.

#### OR

If you want to check the deployed project instead of running it locally:
#### [See Vercel Deploy](https://lucoliv-frontend-challenge.vercel.app/)

### CODE REVIEW

**Comment by vaporwavie** [comment]
Thanks for the submission @luc0liv! @breno5g will take care of your review :)

**Review by breno5g — CHANGES_REQUESTED** [review]
## Errors
### Styling
- #### Header
	- month font weight should be 400 (regular)
	- day font weight should be 300 (light)
	- week font size should be 24px (1.5rem)
- #### Filter Section
	- filter buttons move when selecting
- #### New task input
	- the button is smaller than the input
- #### General
	- we have no visual indication that the buttons are clickable
### Usability
- We have no visual indication that a task is or is not completed
- It is not possible to unmark a completed task.
- It is not possible to edit a task
- the task container is scrolling even when it is not necessary
- If we do not have completed tasks and filter them as "completed", when clicking on the "Clear filters" button we can see that the filter button remains selected.
- the error above applies to the "pending" filter as well.
### Code
- It is not necessary to have a state just for the filtered tasks, because by saving only the filter parameters, we can just filter in the step before rendering
- The task ID is currently a continuous increment of values, so a state was created to know what the last ID is. But the lastId state is reset when we reload the application, thus starting from scratch again, which creates tasks with the repeated id. To simplify this case, it is possible to use the date with milliseconds or an external library such as uuid.
- The triggering of toast is a consequence of the completion of all tasks and not a responsibility for creating new tasks, so it would be logical to use a useEffect for it.
- As in the previous case, the use of "saveToLocalStorage" is not the responsibility of the functions related to editing tasks, it would be more logical to use a useEffect
- The use of the "isFiltered" state becomes redundant, considering that we have the "filter" state which, when filled, already indicates that something is being filtered.
- As previously mentioned at some points, we have a lot of logic repeated in various places in the code, so in order to follow the good principle of DRY (don't repeat yourself) it is recommended to reevaluate some decisions in the code design.

**Comment by vaporwavie** [comment]
@luc0liv let us know if you have any questions. We'll be waiting for the post-CR updates for your projects to move forward. Thank you!

**Comment by luc0liv** [comment]
@breno5g Thank you for your feedback! I'll fix this issues.

**Comment by luc0liv** [comment]
@breno5g Hey, I made the changes you requested.

**Review by breno5g — APPROVED** [review]
## Errors
### Styling
-  month and year font size have to be 24px
-  Using opacity as a hover effect is not recommended, as this can cause accessibility and usability problems depending on the browser. So using filter opacity would be better.
-  We can remove the outline of the selected entry, thus giving a better sense of continuity in this session.
- the cross icon to show the task is completed isn't a good solution, because cross icon usually mean close.
-  to that case, we could add a stroke to text, remove some opacity with a filter or another icon of your choice.
-  the task "completion" effect is triggered again when we edit a completed task.
###  Code 
- Adding text to a react state with each new letter the user types generates a considerable load of state changes for such a simple case. It is recommended to use something like refs to save the input values and just get that value when we use it.
- When searching for a task, it is not necessary to validate whether it is pending, because if it is not completed, pending is the only possible state.
----
## Final considerations
Considering that this is a mid-level position, the initiative to create tests and documentation would be interesting.
But overall, I liked the improvements I saw here and it's good to see that you managed to resolve much of what was highlighted in the previous code review.

Thank you for participating in the technical test and we will get back to you as soon as possible with the next steps.

**Comment by luc0liv** [comment]
@breno5g @vaporwavie  Thank you! I learned a lot from this.

**Comment by vaporwavie** [comment]
Thank you for taking the time on this challenge @luc0liv! Accepting and closing this PR.

**Pull request closed without merging**
